# Node, Mongo, Redis, Nginx
# Minh Chu <scsilver94@gmail.com>
# Andres Separ <andres.separ@gmail.com>

version: "2"
services:
  api:
    image: node:latest
    restart: always
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./api:/home/node/api/
    working_dir: /home/node/api
    command: yarn start
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongo3:
    hostname: mongo3
    image: mongo:latest
    volumes:
      - mongodb/data:/data/db/
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
    ports:
      - "27019:27017"
      - "28019:28017"
    restart: always
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongo2:
    hostname: mongo2
    image: mongo:latest
    volumes:
      - mongodb/data:/data/db/
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
    ports:
      - "27018:27017"
      - "28018:28017"
    restart: always
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongo1:
    hostname: mongo1
    image: mongo:latest
    volumes:
      - mongodb/data:/data/db/
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
    ports:
      - "27017:27017"
      - "28017:28017"
    links:
      - mongo2:mongo2
      - mongo3:mongo3
    restart: always
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongosetup:
    image: mongo:latest
    links:
      - mongo1:mongo1
      - mongo2:mongo2
      - mongo3:mongo3
    volumes:
      - mongodb/replicaset.sh:/replicaset.sh
    entrypoint: [ "replicaset.sh" ]
    restart: always
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    image: redis:latest
    restart: always
    networks:
      - backend
    volumes:
      - redis:/data/
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - api
    networks:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

networks:
  backend:

volumes:
  mongodb:
  redis:
