# Node, Mongo, Redis, Nginx
# Minh Chu <scsilver94@gmail.com>
# Andres Separ <andres.separ@gmail.com>

version: "2"
services:
  api:
    container_name: api
    image: node:latest
    restart: always
    depends_on:
      - mongosetup
      - redis
    volumes:
      - ./api:/home/node/api/
    working_dir: /home/node/api
    command: yarn start
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongo3:
    container_name: mongo3
    hostname: mongo3
    image: mongo:latest
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles" ]
    ports:
      - "27019:27017"
      - "28019:28017"
    restart: always
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongo2:
    container_name: mongo2
    hostname: mongo2
    image: mongo:latest
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles" ]
    ports:
      - "27018:27017"
      - "28018:28017"
    restart: always
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongo1:
    container_name: mongo1
    hostname: mongo1
    image: mongo:latest
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles" ]
    ports:
      - "27017:27017"
      - "28017:28017"
    restart: always
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongosetup:
    container_name: mongo
    image: mongo:latest
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./mongodb/scripts:/scripts
    entrypoint: [ "sh", "/scripts/replicaset.sh" ]
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - backend
    volumes:
      - redis:/data/
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    depends_on:
      - api
    networks:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

networks:
  backend:
    driver: bridge

volumes:
  mongodb:
  redis:
